# Generated by Django 5.0.6 on 2024-07-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
